### ISSUE TITLE
Review existing information models for challenges/benchmarking

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/challenge-schemas#1]
Please include any references or links to others if you find them!

+ [x] The [**Minimal Information About a Challenge** schema](https://github.com/Sage-Bionetworks/MIAC-schema) that @milen-sage created (#4)
+ [x] The Spanish National Bioinformatics Institute (INAB), as part of the [Elixir EXCELERATE](https://elixir-europe.org/about-us/how-funded/eu-projects/excelerate) project, appears to have a benchmarking platform called [**OpenEBench**](https://openebench.bsc.es/html/dashboard) (#2)
  + they have a [benchmarking data model](https://github.com/inab/benchmarking-data-model)
  + and a bunch of [other repos](https://github.com/search?q=topic%3Aopenebench+org%3Ainab&type=Repositories) that might be worth checking out
+ [x] TopCoder doesn't have an overarching data model, per se, but the definitions in their spec for the [**submission API**](https://github.com/topcoder-platform/submissions-api/blob/develop/docs/swagger.yaml) serves as a reasonable approximation (#5)
+ Codalab?
